---
- name: Create temporary download directory if it does not exist
  delegate_to: localhost
  run_once: true
  become: no
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.ansible_download_cache"
    state: directory
    mode: 0755

- block:
    - name: Determine latest GitHub release (local)
      delegate_to: localhost
      become: false
      ansible.builtin.uri:
        url: "https://api.github.com/repos/hashicorp/consul/releases"
        body_format: json
      register: _github_releases
      until: _github_releases.status == 200
      retries: 5

    - name: Set consul_version
      ansible.builtin.set_fact: consul_version="{{ (_github_releases.json | default([])) | json_query('[?prerelease==`false` && draft==`false`].tag_name') | community.general.version_sort | last | regex_replace('^v?(.*)$', '\\1') }}"

  when: (consul_version is not defined) or (consul_version == 'latest')
  run_once: true

- name: Download Consul and verify SHA256 checksum
  delegate_to: localhost
  run_once: true
  become: no
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_arm64.zip"
    dest: "{{ playbook_dir }}/.ansible_download_cache/consul_{{ consul_version }}_linux_arm64.zip"
    checksum: "sha256:https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_SHA256SUMS"
    mode: 0644

- name: Extract Consul
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/.ansible_download_cache/consul_{{ consul_version }}_linux_arm64.zip"
    dest: /usr/bin

- name: Create consul user
  ansible.builtin.user:
    name: consul
    home: /etc/consul.d
    system: yes
    shell: /usr/bin/false
    state: present

- name: Create data directory
  ansible.builtin.file:
    path: "{{ consul_data_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: 0755

- name: Copy config
  ansible.builtin.template:
    src: "consul.hcl.j2"
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul
    mode: 0644

- name: Copy systemd service
  ansible.builtin.template:
    src: "consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    mode: 0644

- name: Start consul service
  ansible.builtin.systemd:
    name: consul
    state: started
    daemon_reload: yes
    enabled: yes
