---
- name: Create temporary download directory if it does not exist
  delegate_to: localhost
  become: no
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.ansible_download_cache"
    state: directory
    mode: 0755

- block:
    - name: Determine latest GitHub release (local)
      delegate_to: localhost
      become: false
      ansible.builtin.uri:
        url: "https://api.github.com/repos/coredns/coredns/releases/latest"
        body_format: json
      register: _github_release
      until: _github_release.status == 200
      retries: 5

    - name: Set coredns_version
      ansible.builtin.set_fact: coredns_version="{{ _github_release.json.tag_name | regex_replace('^v?(.*)$', '\\1') }}"

  when: (coredns_version is not defined) or (coredns_version == 'latest')
  run_once: true

- name: Download CoreDNS and verify SHA256 checksum
  delegate_to: localhost
  become: no
  ansible.builtin.get_url:
    url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_linux_arm64.tgz"
    dest: "{{ playbook_dir }}/.ansible_download_cache/coredns_{{ coredns_version }}_linux_arm64.tgz"
    checksum: "sha256:https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_linux_arm64.tgz.SHA256"
    mode: 0644

- name: Extract CoreDNS
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/.ansible_download_cache/coredns_{{ coredns_version }}_linux_arm64.tgz"
    dest: /usr/bin

- name: Create coredns user
  ansible.builtin.user:
    name: coredns
    home: /etc/coredns
    system: yes
    shell: /usr/bin/false
    state: present

- name: Copy config
  ansible.builtin.template:
    src: "Corefile.j2"
    dest: "/etc/coredns/Corefile"
    mode: 0644

- name: Copy systemd service
  ansible.builtin.copy:
    src: "coredns.service"
    dest: "/etc/systemd/system/coredns.service"
    mode: 0644

- name: Disable systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Set nameserver to localhost
  ansible.builtin.copy:
    content: 'nameserver 127.0.0.1'
    dest: /etc/resolv.conf
    mode: 0644

- name: Start coredns service
  ansible.builtin.systemd:
    name: coredns
    state: restarted
    daemon_reload: yes
    enabled: yes
