---
- name: Update apt cache
  ansible.builtin.apt: update_cache=yes

- name: Install base dependencies
  ansible.builtin.package:
    name:
      - curl
      - dnsutils
      - gnupg2
      - jq
      - unzip
    state: present

- name: Remove "snap" package
  ansible.builtin.apt:
    name: snapd
    state: absent
    autoremove: yes
    purge: yes
  when: ansible_distribution == 'Ubuntu'
